version: "3"

services:
  webapp:
    image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
    ports:
      - ${API_PORT}:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./api/bin:/https:ro
    depends_on:
      - db
  db:
    image: mariadb
    container_name: enigma_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASS}
      MYSQL_DATABASE: enigma
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_USER_PASS}
    volumes: 
      - ./db/mysql:/var/lib/mysql
    ports:
      - ${SQL_PORT}:3306
  adminer:
    image: adminer
    container_name: enigma_dbadmin
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
  nginx:
    image: nginx
    ports:
        - ${UI_PORT}:80
    volumes:
        - ./www/ui:/usr/share/nginx/html